import Gtk from "gi://Gtk";
import Adw from "gi://Adw";
import Gio from "gi://Gio";
import GLib from "gi://GLib";

import {
  ExtensionPreferences,
  gettext as _,
} from "resource:///org/gnome/Shell/Extensions/js/extensions/prefs.js";
import { syncDesktopFiles, updateDesktopDatabase } from "./utils.js";
import { MATCHED_DIR } from "./contants.js";

// TODO: create a file utils
export default class GnomeRectanglePreferences extends ExtensionPreferences {
  _renderDebugToggle(page: Adw.PreferencesPage, settings: Gio.Settings) {
    const debugGroup = new Adw.PreferencesGroup({
      title: _("Debug"),
      description: _("Debug and troubleshooting options"),
    });

    page.add(debugGroup);

    const debugEnabled = new Adw.SwitchRow({
      title: _("Enable debug logs"),
      subtitle: _("Print extension logs to the journal"),
    });

    debugGroup.add(debugEnabled);

    settings.bind(
      "debug",
      debugEnabled,
      "active",
      Gio.SettingsBindFlags.DEFAULT,
    );
  }

  _renderBlacklistedWmClass(page: Adw.PreferencesPage, settings: Gio.Settings) {
    const blacklistGroup = new Adw.PreferencesGroup({
      title: _("Blacklisted WM Classes"),
      description: _("Ignored WM_CLASS patterns"),
    });

    page.add(blacklistGroup);

    const blacklistRow = new Adw.EntryRow({
      title: _("Patterns"),
    });

    blacklistRow.set_text(
      settings.get_strv("blacklisted-wm-classes").join(", "),
    );

    blacklistRow.connect("changed", () => {
      const values = blacklistRow
        .get_text()
        .split(",")
        .map((v) => v.trim())
        .filter(Boolean);

      settings.set_strv("blacklisted-wm-classes", values);
    });

    blacklistGroup.add(blacklistRow);

    const blacklistHelp = new Adw.ActionRow({
      title: _("Pattern examples"),
      subtitle: _(
        "example = exact, example* = prefix, *example = suffix, *example* = contains",
      ),
    });

    blacklistGroup.add(blacklistHelp);
  }

  _renderActionsGroup(
    page: Adw.PreferencesPage,
    window: Adw.PreferencesWindow,
  ) {
    const actionsGroup = new Adw.PreferencesGroup({
      title: _("Actions"),
      description: _("Perform actions on auto generated files."),
    });

    this._renderSyncButton(actionsGroup, window);
    this._renderResetButton(actionsGroup, window);

    page.add(actionsGroup);
  }

  _renderSyncButton(
    group: Adw.PreferencesGroup,
    window: Adw.PreferencesWindow,
  ) {
    const syncButton = new Gtk.Button({
      label: _("Sync (Experimental)"),
      cssClasses: ["action-button"],
      halign: Gtk.Align.END,
      widthRequest: 140,
      heightRequest: 40,
    });

    const resetRow = new Adw.ActionRow({
      title: _("Sync information"),
      subtitle: _(
        "Sync information between the original and autogenerated file.",
      ),
    });

    syncButton.connect("clicked", () => this._onClickSyncButton());

    resetRow.add_suffix(syncButton);
    group.add(resetRow);
  }

  _renderResetButton(
    group: Adw.PreferencesGroup,
    window: Adw.PreferencesWindow,
  ) {
    const resetButton = new Gtk.Button({
      label: _("Reset"),
      cssClasses: ["destructive-action", "action-button"],
      halign: Gtk.Align.END,
      widthRequest: 140,
      heightRequest: 40,
    });

    resetButton.connect("clicked", () => {
      const dialog = new Adw.MessageDialog({
        transientFor: window,
        heading: _("Reset generated desktop files?"),
        body: _(
          "All desktop files generated by the extension will be permanently removed.",
        ),
      });

      dialog.add_response("cancel", _("Cancel"));
      dialog.add_response("confirm", _("Reset"));

      dialog.set_response_appearance(
        "confirm",
        Adw.ResponseAppearance.DESTRUCTIVE,
      );

      dialog.set_default_response("cancel");
      dialog.set_close_response("cancel");

      dialog.connect("response", async (_dialog, response) => {
        if (response !== "confirm") return;

        try {
          await this._onClickResetButton(window);
        } catch (err) {
          console.error(err);
        }
      });

      dialog.present();
    });

    const resetRow = new Adw.ActionRow({
      title: _("Restore defaults"),
      subtitle: _("Delete generated desktop files"),
    });

    resetRow.add_suffix(resetButton);
    group.add(resetRow);
  }

  async _onClickResetButton(window: Adw.PreferencesWindow) {
    const dialog = new Adw.MessageDialog({
      transientFor: window,
      heading: _("Reset generated desktop files?"),
      body: _(
        "All desktop files generated by the extension will be permanently removed.",
      ),
    });

    dialog.add_response("cancel", _("Cancel"));
    dialog.add_response("confirm", _("Reset"));

    dialog.set_response_appearance(
      "confirm",
      Adw.ResponseAppearance.DESTRUCTIVE,
    );

    dialog.set_default_response("cancel");
    dialog.set_close_response("cancel");

    dialog.connect("response", async (_dialog, response) => {
      if (response !== "confirm") return;

      try {
        await this._resetAutoGeneratedFiles();
      } catch (err) {
        console.error(err);
      }
    });
    dialog.present();
  }

  async _resetAutoGeneratedFiles(): Promise<void> {
    const dir = Gio.File.new_for_path(MATCHED_DIR);
    const exists = dir.query_exists(null);
    if (!exists) return;
    const enumerator = dir.enumerate_children(
      "standard::*",
      Gio.FileQueryInfoFlags.NONE,
      null,
    );
    let info: Gio.FileInfo | null;
    while ((info = enumerator.next_file(null))) {
      const child = dir.get_child(info.get_name());
      try {
        child.delete(null);
      } catch (err) {}
    }
    updateDesktopDatabase();
  }

  async _onClickSyncButton(): Promise<void> {
    await syncDesktopFiles(MATCHED_DIR);
    updateDesktopDatabase();
  }

  // TODO: update this deprecated API usage
  fillPreferencesWindow(window: Adw.PreferencesWindow): Promise<void> {
    const settings = this.getSettings();

    const page = new Adw.PreferencesPage({
      title: _("General"),
      iconName: "preferences-system-symbolic",
    });

    this._renderDebugToggle(page, settings);
    this._renderBlacklistedWmClass(page, settings);
    this._renderActionsGroup(page, window);

    window.add(page);

    return Promise.resolve();
  }
}
