import Gtk from "gi://Gtk";
import Adw from "gi://Adw";
import Gio from "gi://Gio";
import GLib from "gi://GLib";

import {
  ExtensionPreferences,
  gettext as _,
} from "resource:///org/gnome/Shell/Extensions/js/extensions/prefs.js";

// TODO: create a shared constat file
const USER_APP_DIR = `${GLib.get_home_dir()}/.local/share/applications`;
const MATCHED_DIR = `${USER_APP_DIR}/icons-matched`;

export default class GnomeRectanglePreferences extends ExtensionPreferences {
  _renderDebugToggle(page: Adw.PreferencesPage, settings: Gio.Settings) {
    const debugGroup = new Adw.PreferencesGroup({
      title: _("Debug"),
      description: _("Debug and troubleshooting options"),
    });

    page.add(debugGroup);

    const debugEnabled = new Adw.SwitchRow({
      title: _("Enable debug logs"),
      subtitle: _("Print extension logs to the journal"),
    });

    debugGroup.add(debugEnabled);

    settings.bind(
      "debug",
      debugEnabled,
      "active",
      Gio.SettingsBindFlags.DEFAULT,
    );
  }

  _renderBlacklistedWmClass(page: Adw.PreferencesPage, settings: Gio.Settings) {
    const blacklistGroup = new Adw.PreferencesGroup({
      title: _("Blacklisted WM Classes"),
      description: _("Ignored WM_CLASS patterns"),
    });

    page.add(blacklistGroup);

    const blacklistRow = new Adw.EntryRow({
      title: _("Patterns"),
    });

    blacklistRow.set_text(
      settings.get_strv("blacklisted-wm-classes").join(", "),
    );

    blacklistRow.connect("changed", () => {
      const values = blacklistRow
        .get_text()
        .split(",")
        .map((v) => v.trim())
        .filter(Boolean);

      settings.set_strv("blacklisted-wm-classes", values);
    });

    blacklistGroup.add(blacklistRow);

    const blacklistHelp = new Adw.ActionRow({
      title: _("Pattern examples"),
      subtitle: _(
        "example = exact, example* = prefix, *example = suffix, *example* = contains",
      ),
    });

    blacklistGroup.add(blacklistHelp);
  }

  _renderResetButton(
    page: Adw.PreferencesPage,
    settings: Gio.Settings,
    window: Adw.PreferencesWindow,
  ) {
    const resetGroup = new Adw.PreferencesGroup({
      title: _("Reset"),
      description: _("Delete generated desktop files"),
    });

    page.add(resetGroup);

    const resetButton = new Gtk.Button({
      label: _("Reset settings"),
      cssClasses: ["destructive-action"],
      halign: Gtk.Align.END,
    });

    resetButton.connect("clicked", () => {
      const dialog = new Adw.MessageDialog({
        transientFor: window,
        heading: _("Reset generated desktop files?"),
        body: _(
          "All desktop files generated by the extension will be permanently removed.",
        ),
      });

      dialog.add_response("cancel", _("Cancel"));
      dialog.add_response("confirm", _("Reset"));

      dialog.set_response_appearance(
        "confirm",
        Adw.ResponseAppearance.DESTRUCTIVE,
      );

      dialog.set_default_response("cancel");
      dialog.set_close_response("cancel");

      dialog.connect("response", async (_dialog, response) => {
        if (response !== "confirm") return;

        try {
          await this._resetGeneratedFiles();
        } catch (err) {
          console.error(err);
        }
      });

      dialog.present();
    });

    const resetRow = new Adw.ActionRow({
      title: _("Restore defaults"),
      subtitle: _("Delete generated desktop files"),
    });

    resetRow.add_suffix(resetButton);
    resetGroup.add(resetRow);
  }

  // TODO: update-desktop-database ~/.local/share/applications
  // TODO: create a file utils
  async _resetGeneratedFiles(): Promise<void> {
    const dir = Gio.File.new_for_path(MATCHED_DIR);
    const exists = dir.query_exists(null);
    if (!exists) return;
    const enumerator = dir.enumerate_children(
      "standard::*",
      Gio.FileQueryInfoFlags.NONE,
      null,
    );
    let info: Gio.FileInfo | null;
    while ((info = enumerator.next_file(null))) {
      const child = dir.get_child(info.get_name());
      try {
        child.delete(null);
      } catch (err) {}
    }
  }

  // TODO: update this deprecated API usage
  fillPreferencesWindow(window: Adw.PreferencesWindow): Promise<void> {
    const settings = this.getSettings();

    const page = new Adw.PreferencesPage({
      title: _("General"),
      iconName: "preferences-system-symbolic",
    });

    this._renderDebugToggle(page, settings);
    this._renderBlacklistedWmClass(page, settings);
    this._renderResetButton(page, settings, window);

    window.add(page);

    return Promise.resolve();
  }
}
